# SPDX-License-Identifier: AGPL-3.0-or-later
# lua-regolith -- minimal-dependency build: cc, GNU make, ar, wget.  No cmake.
# libuv + luv are compiled directly from source lists in mk/uv-source.mk. Use
# gmake on the BSDs.  All shared logic: mk/common.mk.

UV_BUILD := source
include mk/common.mk
