#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# build-luaposix-so.sh OBJ_DIR OUT_DIR
# Env: CC, SHARED_LINK, LUA_MOD_EXT, LINK_LIBS
#
# Links each luaposix .o into a .so at the path implied by its exported
# luaopen_* symbol. This is the loop that turns luaposix's pile of object files
# into the nested .so tree that Lua's require() expects:
#   posix_unistd.o    (luaopen_posix_unistd)    -> posix/unistd.so
#   posix_sys_stat.o  (luaopen_posix_sys_stat)  -> posix/sys/stat.so
#
# sed 's/.* //'  -- last field of the nm line (the symbol name)
# sed 's/^_//'   -- macOS prepends _ to all C symbols
#
# WARNING: There's a limitation buried here, worth knowing even though it's
# dormant: the mapping is ambiguous for module names that themselves contain
# underscores. Lua's own loader handles this — when require("foo.bar_baz")
# loads foo/bar_baz.so, it looks for luaopen_foo_bar_baz — but the reverse
# mapping (what this script does) can't tell foo/bar_baz from foo/bar/baz.
# Every underscore becomes a slash, unconditionally. It works because no
# luaposix module has an underscore in its leaf name. If one ever appeared,
# it'd be silently installed at the wrong depth, and require would miss it
set -eu

objdir=$1; outdir=$2

find "$objdir" -name '*.o' | while read -r obj; do
    # nm -g lists external symbols, one per line, format roughly address T
    # symbolname. The pieces:
    # * grep ' T.*luaopen_' — T is nm's code for "defined in this object's
    #   text (code) section." That letter is load-bearing: an object that calls
    #   into liblua will show U luaL_setfuncs (undefined, imported) lines, and
    #   helper objects might reference luaopen_* symbols without defining them.
    #   Filtering on  T keeps only "this object provides this function."
    # * head -1 — defensively take the first match. In practice each luaposix
    #   object defines exactly one opener; if one ever defined two, we'd build
    #   the module under its first-listed name rather than erroring. A judgment
    #   call in favor of robustness over strictness.
    # * sed 's/.* //;s/^_//' — two substitutions, ;-separated. First: delete
    #   everything up to the last space, leaving just the symbol name (last
    #   field of the line — this is the awk-$NF replacement, chosen back when
    #   the script was generated by printf inside a recipe and $N F would've
    #   needed escaping; now that it's a real file, awk would work fine, but
    #   sed does the job). Second: strip a leading underscore, because Mach-O
    #   (macOS) prepends _ to every C symbol — luaopen_posix_unistd in source
    #   becomes _luaopen_posix_unistd in the object. On Linux/ELF there's no
    #   prefix and this substitution matches nothing.
    # * 2>/dev/null on nm — belt-and-suspenders against nm grumbling on any
    #   weird input; combined with the next line, "can't read symbols" degrades
    #   to "skip."
    sym=$(nm -g "$obj" 2>/dev/null | grep ' T.*luaopen_' | head -1 | sed 's/.* //;s/^_//')
    [ -n "$sym" ] || continue
    # Strip the luaopen_ prefix, then convert every underscore to a slash:
    # luaopen_posix_sys_stat →  posix_sys_stat →  posix/sys/stat. Note | as the
    # sed delimiter in the second expression, since the replacement text is a
    # slash — s/_/\//g would work but reads like a fence falling over.
    relpath=$(echo "$sym" | sed 's/^luaopen_//;s|_|/|g')
    # link this one object into a shared module at the derived path. All four
    # variables come from the make recipe's environment
    mkdir -p "$outdir/$(dirname "$relpath")"
    # shellcheck disable=SC2086 # SHARED_LINK and LINK_LIBS must word-split
    $CC $SHARED_LINK -o "$outdir/$relpath.$LUA_MOD_EXT" "$obj" $LINK_LIBS
done
