#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# lua2c.sh — Convert Lua source files to a C header with byte arrays
#
# Usage:
#   ./scripts/lua2c.sh output.h  mod_name:file.lua  mod_name2:file2.lua ...
#
# Generates a C header with:
#   - A static const unsigned char[] for each module's source
#   - A lua_modules[] table of { name, data, length } structs
#
# Module names use Lua's dot notation (e.g. "posix.version", "term.init").
# The C identifier is derived by replacing dots with underscores.
#
# Dependencies: od, sed, tr — all POSIX.

set -e

outfile="$1"
shift

if [ -z "$outfile" ] || [ $# -eq 0 ]; then
    echo "Usage: $0 output.h name:file [name:file ...]" >&2
    exit 1
fi

cat > "$outfile" <<'EOF'
/* Auto-generated by lua2c.sh — do not edit */

struct lr_lua_module {
    const char *name;
    const unsigned char *data;
    unsigned long len;
};

EOF

# Pass 1: emit byte arrays
for pair in "$@"; do
    name="${pair%%:*}"
    file="${pair#*:}"
    cname=$(echo "$name" | sed 's/\./_/g')

    if [ ! -f "$file" ]; then
        echo "WARNING: $file not found, skipping $name" >&2
        continue
    fi

    printf 'static const unsigned char mod_%s[] = {\n' "$cname" >> "$outfile"

    # Convert file to comma-separated hex bytes.
    #
    # od -An -tx1 -v produces lines of space-separated hex bytes, but
    # the exact formatting varies across platforms (different padding,
    # trailing whitespace, occasional blank lines).
    #
    # awk handles all of this: it splits on whitespace (ignoring
    # blank lines and extra spaces), prefixes each token with 0x,
    # and wraps to a new line every 12 bytes.
    od -An -tx1 -v "$file" \
        | awk '
    BEGIN { n = 0 }
    {
        for (i = 1; i <= NF; i++) {
            if (n % 12 == 0) printf "  "
            printf "0x%s,", $i
            n++
            if (n % 12 == 0) printf "\n"
        }
    }
    END { if (n % 12 != 0) printf "\n" }
    ' >> "$outfile"

    printf '};\n\n' >> "$outfile"
done

# Pass 2: emit the module table
printf 'static const struct lr_lua_module lua_modules[] = {\n' >> "$outfile"
for pair in "$@"; do
    name="${pair%%:*}"
    file="${pair#*:}"
    cname=$(echo "$name" | sed 's/\./_/g')

    [ -f "$file" ] || continue

    printf '    { "%s", mod_%s, sizeof(mod_%s) },\n' "$name" "$cname" "$cname" >> "$outfile"
done
printf '    { NULL, NULL, 0 }\n' >> "$outfile"
printf '};\n' >> "$outfile"
