#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# lua2c.sh — Convert Lua source files to a C header with byte arrays
#
# ============================================================================
# PURPOSE
# ============================================================================
#
# The fully-static lua interpreter needs to be self-contained: no .lua files on
# disk.  This script takes one or more .lua source files and produces a C
# header where each file's contents are stored as a static array of bytes
# (unsigned char[]).  At startup, lr_preload_lua.c feeds these byte arrays to
# luaL_loadbuffer(), which compiles them into Lua functions and registers them
# in package.preload — so require("re") finds the embedded source instead of
# searching the filesystem.
#
# ============================================================================
# USAGE
# ============================================================================
#
#   ./scripts/lua2c.sh output.h  name:file  [name:file ...]
#
# Each argument after the output file is a colon-separated pair:
#   - name: the Lua module name (dot notation), e.g. "posix.version"
#   - file: path to the .lua source file
#
# Example:
#   ./scripts/lua2c.sh build/modules.h  re:lpeg-1.1.0/re.lua  dkjson:dkjson-2.8.lua
#
# ============================================================================
# OUTPUT FORMAT
# ============================================================================
#
# The generated header contains:
#
#   1. A struct definition for the module table entries
#   2. One `static const unsigned char mod_<name>[] = { 0x2d, 0x2d, ... };`
#      per module (the raw bytes of the .lua file)
#   3. A `lua_modules[]` table mapping module names to their byte arrays
#
# lr_preload_lua.c includes this header and iterates lua_modules[] at startup
# to register everything.
#
# ============================================================================
# DEPENDENCIES
# ============================================================================
#
# od, awk, sed — all POSIX standard utilities.
#
# od stands for "octal dump" — it's a POSIX utility that dumps the raw bytes of
# a file in various formats.  Despite the name, it can output in hex, decimal,
# or octal.  We use it with:
#
#   od -An -tx1 -v file
#
#   -An   suppress the address/offset column (we just want the bytes)
#   -tx1  output as hexadecimal, one byte at a time
#   -v    "verbose" — don't collapse repeated identical lines into *
#
# Example output for a file containing "hello\n":
#
#   Linux:   " 68 65 6c 6c 6f 0a"
#   macOS:   "          68  65  6c  6c  6f  0a"
#
# Note: the formatting (padding, spacing) varies between platforms,
# which is why we pipe through awk to normalize it.
#
# ============================================================================

# Exit immediately if any command fails.
set -e

# ---- Argument parsing -------------------------------------------------------
#
# $1 is the output file path.  Everything after that is name:file pairs.
# "shift" removes $1, so "$@" becomes just the pairs.

outfile="$1"
shift

if [ -z "$outfile" ] || [ $# -eq 0 ]; then
    echo "Usage: $0 output.h name:file [name:file ...]" >&2
    exit 1
fi

# ---- Write the header preamble ---------------------------------------------
#
# cat <<'EOF' is a "here document".  The single quotes around EOF mean no
# variable expansion happens inside the block — it's written literally. This
# defines the struct that lr_preload_lua.c uses to iterate the module table.

cat > "$outfile" <<'EOF'
/* Auto-generated by lua2c.sh — do not edit */

struct lr_lua_module {
    const char *name;
    const unsigned char *data;
    unsigned long len;
};

EOF

# ============================================================================
# PASS 1: Emit byte arrays
# ============================================================================
#
# For each module, read its .lua file and write a C array of hex bytes. Example
# output for a tiny file:
#
#   static const unsigned char mod_re[] = {
#     0x2d,0x2d,0x20,0x72,0x65,0x2e,0x6c,0x75,0x61,0x0a,0x2d,0x2d,
#     0x20,0x61,0x20,0x72,0x65,
#   };

for pair in "$@"; do

    # ---- Shell parameter expansion -------------------------------------------
    #
    # ${pair%%:*}  — "delete the longest match of :* from the end"
    #                This gives everything BEFORE the first colon.
    #                Example: "posix.version:/path/to/file.lua" → "posix.version"
    #
    # ${pair#*:}   — "delete the shortest match of *: from the start"
    #                This gives everything AFTER the first colon.
    #                Example: "posix.version:/path/to/file.lua" → "/path/to/file.lua"
    #
    # These are POSIX sh built-in string operations (no external tools needed):
    #   ${var%%pattern}  — remove longest suffix matching pattern
    #   ${var%pattern}   — remove shortest suffix matching pattern
    #   ${var##pattern}  — remove longest prefix matching pattern
    #   ${var#pattern}   — remove shortest prefix matching pattern

    name="${pair%%:*}"
    file="${pair#*:}"

    # ---- Build C identifier from module name ---------------------------------
    #
    # sed 's/\./_/g' replaces every dot with an underscore.
    #   "posix.sys.stat" → "posix_sys_stat"
    #
    # This is needed because C identifiers can't contain dots.
    # The result is used as:  static const unsigned char mod_posix_sys_stat[]

    cname=$(echo "$name" | sed 's/\./_/g')

    # Skip missing files with a warning (don't fail the whole build)
    if [ ! -f "$file" ]; then
        echo "WARNING: $file not found, skipping $name" >&2
        continue
    fi

    printf 'static const unsigned char mod_%s[] = {\n' "$cname" >> "$outfile"

    # ---- Convert .lua file to C hex bytes ------------------------------------
    #
    # This is the core of the script.  We pipe the file through od and awk:
    #
    # STEP 1: od -An -tx1 -v "$file"
    #
    #   Dumps every byte of the file as two-digit hex.  Output looks like:
    #     " 2d 2d 20 72 65 2e 6c 75 61 0a 2d 2d 0a"    (Linux)
    #     "          2d  2d  20  72  65  2e  6c  75"     (macOS, wider spacing)
    #
    #   Some lines may be blank or whitespace-only (especially the last).
    #
    # STEP 2: awk '...'
    #
    #   awk reads the od output line by line.  By default, awk splits each line
    #   on whitespace into fields $1, $2, $3, etc.  NF is the number of fields
    #   on the current line.  Blank/whitespace lines have NF=0, so the inner
    #   for loop simply doesn't execute — no special case needed.
    #
    #   The awk program:
    #
    #     BEGIN { n = 0 }
    #       — Initialize a byte counter before processing starts.
    #
    #     {
    #       for (i = 1; i <= NF; i++) {
    #         — Loop over each hex token on the line (e.g. "2d", "65", "0a").
    #
    #         if (n % 12 == 0) printf "  "
    #           — At the start of every group of 12 bytes, print leading
    #             indentation.  This keeps the C array nicely formatted
    #             with 12 bytes per line.
    #
    #         printf "0x%s,", $i
    #           — Print the hex byte as a C hex literal: "2d" → "0x2d,"
    #             %s inserts the field as a string; we prepend "0x" and
    #             append ",".
    #
    #         n++
    #           — Increment the byte counter.
    #
    #         if (n % 12 == 0) printf "\n"
    #           — After every 12th byte, end the line.  This produces
    #             output like:
    #               0x2d,0x2d,0x20,0x72,0x65,0x2e,0x6c,0x75,0x61,0x0a,0x2d,0x2d,
    #               0x0a,0x6c,0x6f,...
    #       }
    #     }
    #
    #     END { if (n % 12 != 0) printf "\n" }
    #       — If the last line had fewer than 12 bytes, we haven't
    #         printed a newline yet.  Add one so the closing "};" is
    #         on its own line.
    #
    # Why awk instead of sed/tr/paste?
    #   Earlier versions used a sed+tr+paste pipeline, but paste fills short
    #   final lines with empty fields (producing ",,,," in the C output).  awk
    #   naturally handles variable-length input without padding — it just
    #   processes however many fields exist on each line.

    od -An -tx1 -v "$file" \
        | awk '
    BEGIN { n = 0 }
    {
        for (i = 1; i <= NF; i++) {
            if (n % 12 == 0) printf "  "
            printf "0x%s,", $i
            n++
            if (n % 12 == 0) printf "\n"
        }
    }
    END { if (n % 12 != 0) printf "\n" }
    ' >> "$outfile"

    printf '};\n\n' >> "$outfile"
done

# ============================================================================
# PASS 2: Emit the module lookup table
# ============================================================================
#
# This generates a C array of structs that lr_preload_lua.c iterates at
# startup.  Each entry maps a Lua module name to its byte array and length.
#
# sizeof(mod_xxx) works because the arrays are defined as fixed-size (the
# compiler knows their length from the initializer).  This avoids needing to
# store or calculate lengths separately.
#
# The table is NULL-terminated so the loader can iterate with a simple while
# loop.
#
# Example output:
#
#   static const struct lr_lua_module lua_modules[] = {
#       { "re", mod_re, sizeof(mod_re) },
#       { "dkjson", mod_dkjson, sizeof(mod_dkjson) },
#       { NULL, NULL, 0 }
#   };

printf 'static const struct lr_lua_module lua_modules[] = {\n' >> "$outfile"
for pair in "$@"; do
    name="${pair%%:*}"
    file="${pair#*:}"
    cname=$(echo "$name" | sed 's/\./_/g')

    # Skip files that were missing in pass 1 (keeps the two passes consistent)
    [ -f "$file" ] || continue

    printf '    { "%s", mod_%s, sizeof(mod_%s) },\n' "$name" "$cname" "$cname" >> "$outfile"
done
printf '    { NULL, NULL, 0 }\n' >> "$outfile"
printf '};\n' >> "$outfile"
