#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# luaposix-config.sh OUTPUT_HEADER
# Env: CC, CFLAGS (should include the platform feature-test defines).
#
# Generates the HAVE_* config header that luaposix's own build system (luke)
# would normally produce. Luaposix's own build system (luke) normally runs
# feature detection and defines HAVE_* macros that the C sources are riddled
# with (#if defined HAVE_TERMIOS_H, etc.). We bypass luke entirely, so we must
# reproduce that detection. The output header lands in build/luaposix-config.h
# and gets force-fed to every luaposix compilation via -include — processed
# before the source file's own #includes, which is what makes the macros (and
# the trailing fixups) visible everywhere.
#
# Same idea as autoconf's AC_CHECK_HEADERS / AC_CHECK_FUNCS, zero dependencies
# beyond cc: compile (header probes) or compile+link (function probes) a
# minimal program; success => #define. Function probes try -lcrypt first
# (crypt(3) on glibc), then without.
#
# Also emits two fixups that must come AFTER the probes:
#
#   macOS _POSIX_TIMERS: <unistd.h> unconditionally defines it as -1 (no
#   timer_create etc.) even though clock_gettime has worked since 10.12, and
#   luaposix gates clock_gettime on it.  Simply defining a new value wouldn't
#   survive the source file's own #include <unistd.h> -- so this header
#   includes <unistd.h> itself (consuming the include guard), then overrides.
#   The later include becomes a no-op and our value sticks.
#
#   LPOSIX_2001_COMPLIANT: gates ctype.c, sched.c, sys/socket.c, parts of
#   unistd.c (mirrors ext/include/_helpers.c).  Derived after <unistd.h> so
#   _POSIX_VERSION is visible.
set -eu
# Note: commands in an || chain (except the last) are exempt from set -e, and a
# function invoked as an if condition has -e suppressed throughout its body

out=$1
: "${CC:=cc}"
: "${CFLAGS:=}"

workdir=$(mktemp -d)
trap 'rm -rf "$workdir"' EXIT

echo "  luaposix: detecting platform features..."
printf '/* Auto-generated by lua-regolith (scripts/luaposix-config.sh) */\n' > "$out"

probe_compiles() {
    # Check if host OS provides a certain feature by generating probe.c and
    # attempting to compile it. Try with or without libcrypt.
    #
    # Note: if the toolchain itself is broken (bad CC, typo in CFLAGS), you get
    # a silent wall of "= no" instead of a diagnosis. The tell is every probe
    # saying no. When that happens, delete the redirections temporarily and the
    # real error surfaces.
    #
    # shellcheck disable=SC2086  -- CFLAGS must word-split
    $CC $CFLAGS -o "$workdir/probe" "$workdir/probe.c" -lcrypt 2>/dev/null \
      || $CC $CFLAGS -o "$workdir/probe" "$workdir/probe.c" 2>/dev/null
}

# --- header probes ---
for pair in \
    'termios.h:HAVE_TERMIOS_H' \
    'sched.h:HAVE_SCHED_H' \
    'sys/msg.h:HAVE_SYS_MSG_H' \
    'sys/statvfs.h:HAVE_SYS_STATVFS_H' \
    'crypt.h:HAVE_CRYPT_H' \
    'net/if.h:HAVE_NET_IF_H' \
    'linux/netlink.h:HAVE_LINUX_NETLINK_H' \
    'linux/if_packet.h:HAVE_LINUX_IF_PACKET_H' \
; do
    # Each entry is header:MACRO, split with the POSIX parameter-expansion pair
    # you'll now see everywhere in this script:
    #  * ${pair%%:*} — %% deletes the longest suffix matching :*, i.e. from
    #    the first colon to the end →  the text before it. 
    #  * ${pair#*:} — # deletes the shortest prefix matching *:, i.e. through
    #    the first colon →  the text after it.
    hdr=${pair%%:*}; macro=${pair#*:}
    printf '#include <%s>\nint main(void){return 0;}\n' "$hdr" > "$workdir/probe.c"
    if probe_compiles; then
        printf '#define %s 1\n' "$macro" >> "$out"
        echo "    $macro = yes  ($hdr)"
    else
        echo "    $macro = no   ($hdr)"
    fi
done

# --- function probes (compile + link) ---
# Format: 'name:MACRO:header:body' -- peeled apart with POSIX parameter
# expansion (${var%%:*} strips from the end, ${var#*:} from the start).
for pair in \
    'statvfs:HAVE_STATVFS:sys/statvfs.h:struct statvfs buf; statvfs("/", &buf)' \
    'crypt:HAVE_CRYPT:unistd.h:crypt("x","ab")' \
    'copy_file_range:HAVE_COPY_FILE_RANGE:unistd.h:copy_file_range(0,0,1,0,1,0)' \
    'posix_fadvise:HAVE_POSIX_FADVISE:fcntl.h:posix_fadvise(0,0,0,0)' \
    'fdatasync:HAVE_DECL_FDATASYNC:unistd.h:fdatasync(0)' \
    'fdatasync:HAVE_FDATASYNC:unistd.h:fdatasync(0)' \
    'gethostid:HAVE_GETHOSTID:unistd.h:gethostid()' \
    'msgrcv:HAVE_MSGRCV:sys/msg.h:msgrcv(0, (void *)0, 0, 0, 0)' \
    'msgsnd:HAVE_MSGSND:sys/msg.h:msgsnd(0, (void *)0, 0, 0)' \
    'sched_getscheduler:HAVE_SCHED_GETSCHEDULER:sched.h:sched_getscheduler(0)' \
    'sched_setscheduler:HAVE_SCHED_SETSCHEDULER:sched.h:struct sched_param p; sched_setscheduler(0, 0, &p)' \
    'tm_gmtoff:HAVE_TM_GMTOFF:time.h:struct tm t; t.tm_gmtoff = 0' \
    'tm_zone:HAVE_TM_ZONE:time.h:struct tm t; t.tm_zone = (char *)0' \
    'ws_xpixel:HAVE_WS_XPIXEL:sys/ioctl.h:struct winsize w; w.ws_xpixel = 0' \
    'ws_ypixel:HAVE_WS_YPIXEL:sys/ioctl.h:struct winsize w; w.ws_ypixel = 0' \
    'clock_gettime:HAVE_CLOCK_GETTIME:time.h:struct timespec ts; clock_gettime(0, &ts)' \
; do
    func=${pair%%:*}; rest=${pair#*:}
    macro=${rest%%:*}; rest=${rest#*:}
    hdr=${rest%%:*};   body=${rest#*:}
    printf '#include <%s>\nint main(void){%s;return 0;}\n' "$hdr" "$body" > "$workdir/probe.c"
    if probe_compiles; then
        printf '#define %s 1\n' "$macro" >> "$out"
        echo "    $macro = yes  ($func)"
    else
        echo "    $macro = no   ($func)"
    fi
done

cat >> "$out" <<'EOF'

/* macOS _POSIX_TIMERS fixup (see script header) */
#include <unistd.h>
#if defined(HAVE_CLOCK_GETTIME) && defined(_POSIX_TIMERS) && _POSIX_TIMERS == -1
#undef _POSIX_TIMERS
#define _POSIX_TIMERS 200809L
#endif

/* POSIX-2001 compliance (mirrors ext/include/_helpers.c) */
#if !defined LPOSIX_2001_COMPLIANT
#if _POSIX_C_SOURCE >= 200112L || _POSIX_VERSION >= 200112L || _XOPEN_SOURCE >= 600
#define LPOSIX_2001_COMPLIANT 1
#endif
#endif
EOF

echo "  wrote $out"
