/* SPDX-License-Identifier: AGPL-3.0-or-later */
/*
 * lr_preload_lua.c — Register embedded pure-Lua modules into package.preload
 *
 * The actual byte arrays are in the build-generated file
 * lr_lua_module_data.h (produced by the Makefile from the .lua sources).
 * Each entry is a { name, data, length } triple.
 *
 * The loader pushes a function (compiled via luaL_loadbuffer) into
 * package.preload[name].  When require("name") is called, Lua runs
 * that function — identical to loading from disk.
 */

#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
#include "lr_preload_lua.h"

/* Pull in the generated byte arrays and module table */
#include "lr_lua_module_data.h"

void preload_bundled_lua_modules(lua_State *L) {
    luaL_getsubtable(L, LUA_REGISTRYINDEX, LUA_PRELOAD_TABLE);
    for (int i = 0; lua_modules[i].name != NULL; i++) {
        if (luaL_loadbuffer(L,
                (const char *)lua_modules[i].data,
                lua_modules[i].len,
                lua_modules[i].name) != LUA_OK) {
            /* If a module fails to compile, push an error function
             * so require() gives a meaningful message instead of
             * silently falling through to the file searcher. */
            lua_pop(L, 1);  /* pop error string */
            continue;
        }
        lua_setfield(L, -2, lua_modules[i].name);
    }
    lua_pop(L, 1);
}
